
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: dev
        password: dev7master
        url: jdbc:mysql://rds-dev2.cro4hpsofg5i.rds.cn-northwest-1.amazonaws.com.cn:3306/tmp?generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf8
        
        
