server:
    port: 8080

students:
    - id: 1
      name: huangxiaoming
    - id: 2
      name: liuyifei

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: dev
        password: dev
        url: jdbc:mysql://localhost:3306/tmp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8